[package]
name = "ulua-analysis"
description = "Luau type checker and type inference (Rust)."
keywords = [ "luau", "lua", "typechecker", "inference", "types" ]
categories = [ "compilers", "development-tools" ]
version = "0.1.7"

[package.edition]
workspace = true

[package.license]
workspace = true

[package.authors]
workspace = true

[package.repository]
workspace = true

[lib]
crate-type = [ "rlib" ]

[dependencies.bitflags]
workspace = true

[dependencies.hipstr]
workspace = true

[dependencies.memchr]
workspace = true
default-features = false

[dependencies.parking_lot]
workspace = true

[dependencies.strum]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.ulua-ast]
path = "../ulua-ast"
version = "0.1.7"

[dependencies.ulua-bytecode]
path = "../ulua-bytecode"
version = "0.1.7"

[dependencies.ulua-common]
path = "../ulua-common"
version = "0.1.7"

[dependencies.ulua-compiler]
path = "../ulua-compiler"
version = "0.1.7"

[dependencies.ulua-config]
path = "../ulua-config"
version = "0.1.7"

[dependencies.ulua-vm]
path = "../ulua-vm"
version = "0.1.7"

[dev-dependencies.ulua-unit-test]
path = "../ulua-unit-test"
version = "0.1.4"

[target."cfg(windows)".dependencies.windows-sys]
workspace = true
features = [ "Win32_System_Memory" ]

[target."cfg(not(target_arch = \"wasm32\"))".dependencies.coarsetime]
workspace = true
