[package]
name = "ulua-capi"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "The Luau VM C ABI symbol export shell (Rust)."
keywords = ["luau", "lua", "vm", "ffi", "c-abi"]
categories = ["external-ffi-bindings", "emulators"]

[lib]
crate-type = ["rlib"]

[dependencies]
ulua-vm = { path = "../ulua-vm", version = "0.1.2" }
