//! The shared skeleton behind every per-`LuaState` side table in this crate.
//!
//! Several features (`app_data`, `async`, `interrupt`, `memory`, `luau_ext`)
//! need to hang Rust state off a VM that the C VM itself cannot hold. All of
//! them have the same shape: a map from *VM identity* to a Rust value, cleared
//! when the VM is dropped. Getting that shape right has exactly two rules, so
//! they are written once here instead of once per feature:
//!
//! 1. **The key is the VM's `global_State` address, not the `LuaState`
//!    address.** A VM owns many coroutine states; `global_State` is the one
//!    they all share, so a hook reached from any of them finds the same entry.
//!    The address is only unique *while the VM is alive*, which is why every
//!    store must be cleared during `LuaInner::drop` (see [`crate::state`],
//!    which runs those hooks in a fixed order): a leftover entry is handed to
//!    the next VM whose allocation happens to reuse that address.
//! 2. **The storage must be reachable from whichever thread drives the VM.**
//!    Without `send` the VM cannot leave its thread, so a `thread_local!` map
//!    is both correct and free. Under `send`, [`crate::Lua`] is `Send`: the VM
//!    can be created on one thread and driven (and dropped) on another, so a
//!    thread-local would strand the entry — the value is never dropped again,
//!    *and* the next VM to reuse the address on the origin thread inherits it.
//!    There the map is a process-wide `parking_lot::Mutex<..>`（无投毒语义，
//!    与 cpp `std::mutex` 一致）, the shape the
//!    async state table already used; different VMs on different threads still
//!    run concurrently, hence the lock, while per-VM access stays serialized
//!    by the `send` contract.
//!
//! Rule 2 is what forces a store's value type to be `Send` under the `send`
//! feature: `Mutex<T>: Sync` requires `T: Send`. Keys are plain `usize`
//! precisely so they satisfy it, and value types that wrap C-owned pointers or
//! user closures say so explicitly (see `memory::MemoryControl`,
//! `interrupt::InterruptFn`, `app_data::Payload`).

use ulua_common::collections::HashMap;

use crate::{state::Lua, sys::LuaState};

/// A per-VM side-table key: the VM's `global_State` address as an integer.
///
/// Compared and used as a map key only, never dereferenced as a pointer. `usize`
/// rather than a raw pointer so that a store stays `Send` under the `send`
/// feature (raw pointers are not).
pub(crate) type VmKey = usize;

/// The map shape every store generated by [`define_vm_store!`] wraps.
pub(crate) type VmMap<T> = HashMap<VmKey, T>;

/// The identity key for `state`'s VM: `(*state).global`.
///
/// The `global_State` is process-unique while the VM is alive and shared by all
/// of the VM's coroutine states, so a hook reached from any of them — a C
/// callback, the interrupt trampoline, the allocator — computes the same key.
///
/// # Safety
/// `state` must be a live `LuaState` belonging to an open VM.
#[inline]
pub(crate) unsafe fn vm_key(state: *mut LuaState) -> VmKey {
  // Safety: 契约要求 `state` 为存活 VM 的 `LuaState`，故 `global` 字段可读；
  // 只把地址转成整数当 key，不解引用。
  unsafe { (*state).global as usize }
}

/// `&Lua` 句柄 → 全局状态整数 key：各 per-VM 侧表（app_data、luau_ext 等）
/// 「按句柄取 key 再操作侧表」的调用点共用这一处最小封装，[`vm_key`] 的
/// unsafe 契约随之内聚（原 `app_data.rs` / `luau_ext.rs` 各持一份同形副本，
/// 现收敛为单源；raw-state 形态的调用点仍直接用 [`vm_key`]）。
#[inline]
pub(crate) fn vm_key_of(lua: &Lua) -> VmKey {
  let state = lua.state();
  // Safety: `state` 存活（`lua` 的 `XRc<LuaInner>` 持有），`vm_key` 按其
  // `unsafe fn` 契约只读其 `global` 指针的地址作整数 key，不解引用。
  unsafe { vm_key(state) }
}

/// Defines a per-VM side table: a unit struct `$name` owning a map from
/// [`VmKey`] to `$value`.
///
/// The struct exposes exactly one operation, `with`:
///
/// * `$name::with(f)` runs `f` with exclusive access to the map, which `f` may
///   mutate in place (`insert`, `remove`, `entry(..).or_default()`, ..).
///
/// The backing store is a `thread_local!` without `send` and a process-wide
/// `Mutex` with it — see the [module docs](self) for why that switch is the
/// whole point. `$value` must be `Send`: the bound is only load-bearing under
/// `send`, where the `Mutex` shape is selected and a stranded entry is
/// otherwise possible.
///
/// Do not call `with` again on the same store from inside `f`: the `RefCell`
/// panics and the `Mutex` deadlocks.
///
/// ```ignore
/// define_vm_store! {
///   /// Per-VM interrupt closure.
///   InterruptStore, InterruptFn
/// }
///
/// InterruptStore::with(|m| m.insert(key, cb));
/// ```
macro_rules! define_vm_store {
  (
    $(#[$attr:meta])*
    $name:ident, $value:ty
  ) => {
    $(#[$attr])*
    pub(crate) struct $name;

    impl $name {
      /// Run `f` with exclusive access to the table. See the [macro
      /// docs](crate::vm_store::define_vm_store) for the nesting rule.
      #[cfg(feature = "send")]
      #[inline]
      pub(crate) fn with<R>(f: impl FnOnce(&mut $crate::vm_store::VmMap<$value>) -> R) -> R {
        use parking_lot::Mutex;
        use std::sync::LazyLock;

        static STORE: LazyLock<Mutex<$crate::vm_store::VmMap<$value>>> =
          LazyLock::new(|| Mutex::new($crate::vm_store::VmMap::default()));

        let mut guard = STORE.lock();
        f(&mut guard)
      }

      /// Run `f` with exclusive access to the table. See the [macro
      /// docs](crate::vm_store::define_vm_store) for the nesting rule.
      #[cfg(not(feature = "send"))]
      #[inline]
      pub(crate) fn with<R>(f: impl FnOnce(&mut $crate::vm_store::VmMap<$value>) -> R) -> R {
        use std::cell::RefCell;

        thread_local! {
          static STORE: RefCell<$crate::vm_store::VmMap<$value>> =
            RefCell::new($crate::vm_store::VmMap::default());
        }

        STORE.with(|s| f(&mut s.borrow_mut()))
      }
    }
  };
}

pub(crate) use define_vm_store;
