[package]
name = "ulua-cli-test"
version = "0.1.4"
publish = false

[package.edition]
workspace = true

[lib]
crate-type = [ "rlib" ]

[dependencies.memchr]
workspace = true
default-features = false

[dependencies.ulua-cli-lib]
path = "../ulua-cli-lib"
version = "0.1.7"

[dependencies.ulua-common]
path = "../ulua-common"
version = "0.1.7"

[dependencies.ulua-config]
path = "../ulua-config"
version = "0.1.7"

[dependencies.ulua-repl-cli]
path = "../ulua-repl-cli"
version = "0.1.7"

[dependencies.ulua-require]
path = "../ulua-require"
version = "0.1.7"

[dependencies.ulua-vm]
path = "../ulua-vm"
version = "0.1.7"

[dev-dependencies.tempfile]
workspace = true
