[package]
name = "ulua-ast-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Luau AST dump CLI (Rust)."
keywords = ["luau", "lua", "ast", "parser", "cli"]
categories = ["command-line-utilities", "development-tools"]

[lib]
crate-type = ["rlib"]

[[bin]]
name = "ulua-ast"
path = "src/main.rs"

[dependencies]
ulua-analysis = { path = "../ulua-analysis", version = "0.1.1" }
ulua-ast = { path = "../ulua-ast", version = "0.1.1" }
ulua-bytecode = { path = "../ulua-bytecode", version = "0.1.1" }
ulua-cli-lib = { path = "../ulua-cli-lib", version = "0.1.1" }
ulua-common = { path = "../ulua-common", version = "0.1.1" }
ulua-compiler = { path = "../ulua-compiler", version = "0.1.1" }
ulua-config = { path = "../ulua-config", version = "0.1.1" }
ulua-vm = { path = "../ulua-vm", version = "0.1.1" }

[features]
default = ["std"]
std = []
native = ["std"]
cli = ["native"]
native-codegen = ["native"]
wasm = []

