[package]
name = "ulua-web"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "WebAssembly bindings to run and type-check Luau in the browser (Rust)."
keywords = ["luau", "lua", "wasm", "webassembly", "playground"]
categories = ["wasm", "web-programming"]

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
ulua-analysis = { path = "../ulua-analysis", version = "0.1.1" }
ulua-ast = { path = "../ulua-ast", version = "0.1.1" }
ulua-bytecode = { path = "../ulua-bytecode", version = "0.1.1" }
ulua-common = { path = "../ulua-common", version = "0.1.1" }
ulua-compiler = { path = "../ulua-compiler", version = "0.1.1" }
ulua-config = { path = "../ulua-config", version = "0.1.1" }
ulua-vm = { path = "../ulua-vm", version = "0.1.1" }

[features]
default = ["std"]
std = []
native = ["std"]
cli = ["native"]
native-codegen = ["native"]
wasm = ["dep:wasm-bindgen", "dep:console_error_panic_hook"]

