export const GITHUB_REPO = "webc-site/ulua",
  GITHUB_URL = "https://github.com/" + GITHUB_REPO,
  X_URL = "https://x.com/iwebcsite",
  BLUESKY_URL = "https://bsky.app/profile/webc-site.bsky.social",
  crateGithubUrlGet = (name) => GITHUB_URL + "/tree/main/crates/" + name,
  crateGithubUrl = crateGithubUrlGet,
  LUAU_UPSTREAM_URL = "https://github.com/luau-lang/luau",
  LUAU_DOCS_URL = "https://luau.org",
  CRATE_LI = [
    "ulua",
    "ulua-rt",
    "ulua-common",
    "ulua-ast",
    "ulua-bytecode",
    "ulua-compiler",
    "ulua-codegen",
    "ulua-vm",
    "ulua-analysis",
    "ulua-config",
    "ulua-require",
    "ulua-web",
  ],
  CRATES_LI = CRATE_LI;
