use core::ptr::{null, null_mut};

use ulua_vm::records::lua_node::LuaNode;

use crate::{
  records::native_fn::{
    GateFn, NativeArithFn, NativeCBarrierbackFn, NativeCBarrierfFn, NativeCBarriertableFn,
    NativeCStepFn, NativeCallEpilogCFn, NativeCallFallbackFn, NativeCallObsHookFn, NativeCallPrologFn,
  NativeCompareFn,
    NativeConcatFn, NativeDolenFn, NativeExecuteGetvarargsConstFn,
    NativeExecuteGetvarargsMultRetFn, NativeExecuteOpcodeFn, NativeFCloseFn, NativeFFindupvalFn,
    NativeFNewLclosureFn, NativeForgLoopFallbackFn, NativeForgLoopIterFn, NativeForgPrepXnextFn,
    NativeGetImportFn, NativeHCloneFn, NativeHGetnFn, NativeHNewFn, NativeHResizearrayFn,
    NativeHSetnumFn, NativeMathBinaryFn, NativeMathFrexpFn, NativeMathLdexpFn, NativeMathModfFn,
    NativeMathUnaryFn, NativeNewUserdataFn, NativeTGettmFn, NativeTObjtypenamestrFn,
    NativeTableAccessFn,
  },
  type_aliases::api::LuauFastFunction,
};

#[derive(Debug, Clone, Copy)]
#[repr(C)]
pub struct NativeContext {
  /// JIT gate 入口，由 `init_header_functions` 注册（ABI 契约见 `native_fn::GateFn`）；
  /// `gate_exit` 是生成码经 `offset_of!` 直读的跳转目标，保持裸代码地址。
  pub gate_entry: Option<GateFn>,
  pub gate_exit: *mut u8,

  /// 空哈希哨兵静态地址（ulua-vm `DUMMYNODE`）：J4b `CheckNodeInsertable` 生成码
  /// 经 `offset_of!` 直读并与 `LuaTable.node` 比较，判「哨兵表 → 插入需 rehash」。
  pub dummynode: *const LuaNode,

  pub lua_v_lessthan: Option<NativeCompareFn>,
  pub lua_v_lessequal: Option<NativeCompareFn>,
  pub lua_v_equalval: Option<NativeCompareFn>,
  pub lua_v_doarithadd: Option<NativeArithFn>,
  pub lua_v_doarithsub: Option<NativeArithFn>,
  pub lua_v_doarithmul: Option<NativeArithFn>,
  pub lua_v_doarithdiv: Option<NativeArithFn>,
  pub lua_v_doarithidiv: Option<NativeArithFn>,
  pub lua_v_doarithmod: Option<NativeArithFn>,
  pub lua_v_doarithpow: Option<NativeArithFn>,
  pub lua_v_doarithunm: Option<NativeArithFn>,
  pub lua_v_dolen: Option<NativeDolenFn>,
  pub lua_v_gettable: Option<NativeTableAccessFn>,
  pub lua_v_settable: Option<NativeTableAccessFn>,
  pub lua_v_concat: Option<NativeConcatFn>,

  pub lua_h_getn: Option<NativeHGetnFn>,
  pub lua_h_new: Option<NativeHNewFn>,
  pub lua_h_clone: Option<NativeHCloneFn>,
  pub lua_h_resizearray: Option<NativeHResizearrayFn>,
  pub lua_h_setnum: Option<NativeHSetnumFn>,

  pub lua_c_barriertable: Option<NativeCBarriertableFn>,
  pub lua_c_barrierf: Option<NativeCBarrierfFn>,
  pub lua_c_barrierback: Option<NativeCBarrierbackFn>,
  pub lua_c_step: Option<NativeCStepFn>,

  pub lua_f_close: Option<NativeFCloseFn>,
  pub lua_f_findupval: Option<NativeFFindupvalFn>,
  pub lua_f_new_lclosure: Option<NativeFNewLclosureFn>,

  pub lua_t_gettm: Option<NativeTGettmFn>,
  pub lua_t_objtypenamestr: Option<NativeTObjtypenamestrFn>,

  pub libm_exp: Option<NativeMathUnaryFn>,
  pub libm_pow: Option<NativeMathBinaryFn>,
  pub libm_fmod: Option<NativeMathBinaryFn>,
  pub libm_asin: Option<NativeMathUnaryFn>,
  pub libm_sin: Option<NativeMathUnaryFn>,
  pub libm_sinh: Option<NativeMathUnaryFn>,
  pub libm_acos: Option<NativeMathUnaryFn>,
  pub libm_cos: Option<NativeMathUnaryFn>,
  pub libm_cosh: Option<NativeMathUnaryFn>,
  pub libm_atan: Option<NativeMathUnaryFn>,
  pub libm_atan2: Option<NativeMathBinaryFn>,
  pub libm_tan: Option<NativeMathUnaryFn>,
  pub libm_tanh: Option<NativeMathUnaryFn>,
  pub libm_log: Option<NativeMathUnaryFn>,
  pub libm_log2: Option<NativeMathUnaryFn>,
  pub libm_log10: Option<NativeMathUnaryFn>,
  pub libm_ldexp: Option<NativeMathLdexpFn>,
  pub libm_round: Option<NativeMathUnaryFn>,
  pub libm_frexp: Option<NativeMathFrexpFn>,
  pub libm_modf: Option<NativeMathModfFn>,

  pub forg_loop_table_iter: Option<NativeForgLoopIterFn>,
  pub forg_loop_node_iter: Option<NativeForgLoopIterFn>,
  pub forg_loop_non_table_fallback: Option<NativeForgLoopFallbackFn>,
  pub forg_prep_xnext_fallback: Option<NativeForgPrepXnextFn>,
  pub call_prolog: Option<NativeCallPrologFn>,
  pub call_obs_hook: Option<NativeCallObsHookFn>,
  pub call_epilog_c: Option<NativeCallEpilogCFn>,
  pub new_userdata: Option<NativeNewUserdataFn>,
  pub get_import: Option<NativeGetImportFn>,

  pub call_fallback: Option<NativeCallFallbackFn>,

  pub execute_getglobal: Option<NativeExecuteOpcodeFn>,
  pub execute_setglobal: Option<NativeExecuteOpcodeFn>,
  pub execute_gettableks: Option<NativeExecuteOpcodeFn>,
  pub execute_settableks: Option<NativeExecuteOpcodeFn>,
  pub execute_namecall: Option<NativeExecuteOpcodeFn>,
  pub execute_setlist: Option<NativeExecuteOpcodeFn>,
  pub execute_forgprep: Option<NativeExecuteOpcodeFn>,
  pub execute_getvarargsmult_ret: Option<NativeExecuteGetvarargsMultRetFn>,
  pub execute_getvarargsconst: Option<NativeExecuteGetvarargsConstFn>,
  pub execute_dupclosure: Option<NativeExecuteOpcodeFn>,
  pub execute_prepvarargs: Option<NativeExecuteOpcodeFn>,

  pub luau_f_table: [LuauFastFunction; 256],
}

impl Default for NativeContext {
  /// 「未挂钩」态逐字段显式构造：函数槽全 `None`、gate 地址为 null、FASTCALL 表全
  /// `None` 槽——与原 `mem::zeroed()` 位位等价（本结构全部字段为指针/`Option<fn>`，
  /// None/null 即零位），但免除 unsafe 并让每个槽位的缺席语义显式化（review.md §2）。
  fn default() -> Self {
    const NO_FASTCALL: LuauFastFunction = None;
    Self {
      gate_entry: None,
      gate_exit: null_mut(),
      dummynode: null(),
      lua_v_lessthan: None,
      lua_v_lessequal: None,
      lua_v_equalval: None,
      lua_v_doarithadd: None,
      lua_v_doarithsub: None,
      lua_v_doarithmul: None,
      lua_v_doarithdiv: None,
      lua_v_doarithidiv: None,
      lua_v_doarithmod: None,
      lua_v_doarithpow: None,
      lua_v_doarithunm: None,
      lua_v_dolen: None,
      lua_v_gettable: None,
      lua_v_settable: None,
      lua_v_concat: None,
      lua_h_getn: None,
      lua_h_new: None,
      lua_h_clone: None,
      lua_h_resizearray: None,
      lua_h_setnum: None,
      lua_c_barriertable: None,
      lua_c_barrierf: None,
      lua_c_barrierback: None,
      lua_c_step: None,
      lua_f_close: None,
      lua_f_findupval: None,
      lua_f_new_lclosure: None,
      lua_t_gettm: None,
      lua_t_objtypenamestr: None,
      libm_exp: None,
      libm_pow: None,
      libm_fmod: None,
      libm_asin: None,
      libm_sin: None,
      libm_sinh: None,
      libm_acos: None,
      libm_cos: None,
      libm_cosh: None,
      libm_atan: None,
      libm_atan2: None,
      libm_tan: None,
      libm_tanh: None,
      libm_log: None,
      libm_log2: None,
      libm_log10: None,
      libm_ldexp: None,
      libm_round: None,
      libm_frexp: None,
      libm_modf: None,
      forg_loop_table_iter: None,
      forg_loop_node_iter: None,
      forg_loop_non_table_fallback: None,
      forg_prep_xnext_fallback: None,
      call_prolog: None,
      call_obs_hook: None,
      call_epilog_c: None,
      new_userdata: None,
      get_import: None,
      call_fallback: None,
      execute_getglobal: None,
      execute_setglobal: None,
      execute_gettableks: None,
      execute_settableks: None,
      execute_namecall: None,
      execute_setlist: None,
      execute_forgprep: None,
      execute_getvarargsmult_ret: None,
      execute_getvarargsconst: None,
      execute_dupclosure: None,
      execute_prepvarargs: None,
      luau_f_table: [NO_FASTCALL; 256],
    }
  }
}
