// 由脚本生成：仅声明 conformance 用到的子模块。
#[path = "assert_inliner_data.rs"]
pub mod assert_inliner_data;
#[path = "bytecode_types.rs"]
pub mod bytecode_types;
#[path = "c_file_ref.rs"]
pub mod c_file_ref;
#[path = "conformance_debugger_state.rs"]
pub mod conformance_debugger_state;
#[path = "conformance_gc_dump_enum_context.rs"]
pub mod conformance_gc_dump_enum_context;
#[path = "conformance_interrupt_error_inspection_state.rs"]
pub mod conformance_interrupt_error_inspection_state;
#[path = "conformance_interrupt_state.rs"]
pub mod conformance_interrupt_state;
#[path = "conformance_tag_method_error_state.rs"]
pub mod conformance_tag_method_error_state;
#[path = "direct_field_access_handler_hit_count.rs"]
pub mod direct_field_access_handler_hit_count;
#[path = "exception_result.rs"]
pub mod exception_result;
#[path = "feedback_vector_fixture.rs"]
pub mod feedback_vector_fixture;
#[path = "heap.rs"]
pub mod heap;
#[path = "heap_edge.rs"]
pub mod heap_edge;
#[path = "heap_node.rs"]
pub mod heap_node;
#[path = "scoped_f_value.rs"]
pub mod scoped_f_value;
#[path = "state_ref.rs"]
pub mod state_ref;
#[path = "userdata_tags.rs"]
pub mod userdata_tags;
#[path = "vec_2_conformance_ir_hooks.rs"]
pub mod vec_2_conformance_ir_hooks;
#[path = "vec_2_direct_field_access_test.rs"]
pub mod vec_2_direct_field_access_test;
#[path = "vertex.rs"]
pub mod vertex;
