[package]
name = "ulua-compile-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Command-line Luau source-to-bytecode compiler (Rust)."
keywords = ["luau", "lua", "compiler", "bytecode", "cli"]
categories = ["command-line-utilities", "compilers"]

[lib]
crate-type = ["rlib"]

[[bin]]
name = "ulua-compile"
path = "src/main.rs"

[dependencies]
ulua-ast = { path = "../ulua-ast", version = "0.1.1" }
ulua-bytecode = { path = "../ulua-bytecode", version = "0.1.1" }
ulua-cli-lib = { path = "../ulua-cli-lib", version = "0.1.1" }
ulua-code-gen = { path = "../ulua-code-gen", version = "0.1.1" }
ulua-common = { path = "../ulua-common", version = "0.1.1" }
ulua-compiler = { path = "../ulua-compiler", version = "0.1.1" }
ulua-vm = { path = "../ulua-vm", version = "0.1.1" }

[features]
default = ["std"]
std = []
native = ["std"]
cli = ["native"]
native-codegen = ["native"]
wasm = []

