[package]
name = "ulua-compile-cli"
description = "Command-line Luau source-to-bytecode compiler (Rust)."
keywords = [ "luau", "lua", "compiler", "bytecode", "cli" ]
categories = [ "command-line-utilities", "compilers" ]

[package.version]
workspace = true

[package.edition]
workspace = true

[package.license]
workspace = true

[package.authors]
workspace = true

[package.repository]
workspace = true

[lib]
crate-type = [ "rlib" ]

[[bin]]
name = "ulua-compile"
path = "src/main.rs"

[dependencies.ulua-ast]
path = "../ulua-ast"
version = "0.1.4"

[dependencies.ulua-bytecode]
path = "../ulua-bytecode"
version = "0.1.4"

[dependencies.ulua-cli-lib]
path = "../ulua-cli-lib"
version = "0.1.4"

[dependencies.ulua-code-gen]
path = "../ulua-code-gen"
version = "0.1.4"

[dependencies.ulua-common]
path = "../ulua-common"
version = "0.1.4"

[dependencies.ulua-compiler]
path = "../ulua-compiler"
version = "0.1.4"

[dependencies.ulua-vm]
path = "../ulua-vm"
version = "0.1.4"

[dependencies.rayon]
workspace = true

[dev-dependencies.ulua-cli-lib]
path = "../ulua-cli-lib"
features = [ "test-utils" ]
