// 由脚本生成：仅声明 ir_lowering 用到的子模块。
#[path = "luau_library_constant_lookup.rs"]
pub mod luau_library_constant_lookup;
#[path = "luau_library_type_lookup.rs"]
pub mod luau_library_type_lookup;
#[path = "type_to_userdata_index.rs"]
pub mod type_to_userdata_index;
#[path = "userdata_access.rs"]
pub mod userdata_access;
#[path = "userdata_access_bytecode_type.rs"]
pub mod userdata_access_bytecode_type;
#[path = "userdata_index_to_type.rs"]
pub mod userdata_index_to_type;
#[path = "userdata_metamethod.rs"]
pub mod userdata_metamethod;
#[path = "userdata_metamethod_bytecode_type.rs"]
pub mod userdata_metamethod_bytecode_type;
#[path = "userdata_namecall.rs"]
pub mod userdata_namecall;
#[path = "userdata_namecall_bytecode_type.rs"]
pub mod userdata_namecall_bytecode_type;
#[path = "vector_access.rs"]
pub mod vector_access;
#[path = "vector_access_bytecode_type.rs"]
pub mod vector_access_bytecode_type;
#[path = "vector_namecall.rs"]
pub mod vector_namecall;
#[path = "vector_namecall_bytecode_type.rs"]
pub mod vector_namecall_bytecode_type;
