// 由脚本生成：仅声明 conformance 用到的子模块。
#[path = "alloc.rs"]
pub mod alloc;
#[path = "analyze_file.rs"]
pub mod analyze_file;
#[path = "blockable_realloc.rs"]
pub mod blockable_realloc;
#[path = "blockable_realloc_allowed.rs"]
pub mod blockable_realloc_allowed;
#[path = "c_yielding_iterator.rs"]
pub mod c_yielding_iterator;
#[path = "c_yielding_iterator_continuation.rs"]
pub mod c_yielding_iterator_continuation;
#[path = "conformance_api_atoms_useratom.rs"]
pub mod conformance_api_atoms_useratom;
#[path = "conformance_api_calls_check_not_yieldable.rs"]
pub mod conformance_api_calls_check_not_yieldable;
#[path = "conformance_c_yield_setup.rs"]
pub mod conformance_c_yield_setup;
#[path = "conformance_coverage_callback.rs"]
pub mod conformance_coverage_callback;
#[path = "conformance_coverage_getcoverage.rs"]
pub mod conformance_coverage_getcoverage;
#[path = "conformance_coverage_setup.rs"]
pub mod conformance_coverage_setup;
#[path = "conformance_debugger_breakpoint.rs"]
pub mod conformance_debugger_breakpoint;
#[path = "conformance_debugger_debug_break.rs"]
pub mod conformance_debugger_debug_break;
#[path = "conformance_debugger_debug_interrupt.rs"]
pub mod conformance_debugger_debug_interrupt;
#[path = "conformance_debugger_debug_step.rs"]
pub mod conformance_debugger_debug_step;
#[path = "conformance_debugger_setup.rs"]
pub mod conformance_debugger_setup;
#[path = "conformance_debugger_yield.rs"]
pub mod conformance_debugger_yield;
#[path = "conformance_exception_object_capture_exception.rs"]
pub mod conformance_exception_object_capture_exception;
#[path = "conformance_gc_dump_edge.rs"]
pub mod conformance_gc_dump_edge;
#[path = "conformance_gc_dump_node.rs"]
pub mod conformance_gc_dump_node;
#[path = "conformance_gc_set_block_allocations.rs"]
pub mod conformance_gc_set_block_allocations;
#[path = "conformance_gc_setup.rs"]
pub mod conformance_gc_setup;
#[path = "conformance_interrupt_error_inspection_interrupt.rs"]
pub mod conformance_interrupt_error_inspection_interrupt;
#[path = "conformance_interrupt_inspection_hook.rs"]
pub mod conformance_interrupt_inspection_hook;
#[path = "conformance_interrupt_inspection_interrupt.rs"]
pub mod conformance_interrupt_inspection_interrupt;
#[path = "conformance_interrupt_inspection_setup.rs"]
pub mod conformance_interrupt_inspection_setup;
#[path = "conformance_interrupt_inspection_yield.rs"]
pub mod conformance_interrupt_inspection_yield;
#[path = "conformance_interrupt_interrupt.rs"]
pub mod conformance_interrupt_interrupt;
#[path = "conformance_iter_setup.rs"]
pub mod conformance_iter_setup;
#[path = "conformance_jit_inliner_interrupt.rs"]
pub mod conformance_jit_inliner_interrupt;
#[path = "conformance_n_debug_get_up_value_yield.rs"]
pub mod conformance_n_debug_get_up_value_yield;
#[path = "conformance_native_type_annotations_setup.rs"]
pub mod conformance_native_type_annotations_setup;
#[path = "conformance_native_userdata_remapper.rs"]
pub mod conformance_native_userdata_remapper;
#[path = "conformance_native_userdata_setup.rs"]
pub mod conformance_native_userdata_setup;
#[path = "conformance_new_userdata_overflow_callback.rs"]
pub mod conformance_new_userdata_overflow_callback;
#[path = "conformance_new_userdata_overflow_dtor.rs"]
pub mod conformance_new_userdata_overflow_dtor;
#[path = "conformance_p_call_resume_error.rs"]
pub mod conformance_p_call_resume_error;
#[path = "conformance_p_call_setup.rs"]
pub mod conformance_p_call_setup;
#[path = "conformance_reference_dtor.rs"]
pub mod conformance_reference_dtor;
#[path = "conformance_reference_dtor_hits.rs"]
pub mod conformance_reference_dtor_hits;
#[path = "conformance_tables_make_lud.rs"]
pub mod conformance_tables_make_lud;
#[path = "conformance_tables_setup.rs"]
pub mod conformance_tables_setup;
#[path = "conformance_tag_method_error_debug_protected_error.rs"]
pub mod conformance_tag_method_error_debug_protected_error;
#[path = "conformance_tag_method_error_setup.rs"]
pub mod conformance_tag_method_error_setup;
#[path = "conformance_tag_method_error_yield.rs"]
pub mod conformance_tag_method_error_yield;
#[path = "conformance_types_setup.rs"]
pub mod conformance_types_setup;
#[path = "conformance_userdata_direct_access_setup.rs"]
pub mod conformance_userdata_direct_access_setup;
#[path = "conformance_userdata_direct_access_useratom.rs"]
pub mod conformance_userdata_direct_access_useratom;
#[path = "conformance_userdata_setup.rs"]
pub mod conformance_userdata_setup;
#[path = "conformance_vector_setup.rs"]
pub mod conformance_vector_setup;
#[path = "cpcall_test.rs"]
pub mod cpcall_test;
#[path = "cxxthrow.rs"]
pub mod cxxthrow;
#[path = "default_codegen_options.rs"]
pub mod default_codegen_options;
#[path = "direct_field_access_counted_get_999_number.rs"]
pub mod direct_field_access_counted_get_999_number;
#[path = "direct_field_access_counted_get_x_number.rs"]
pub mod direct_field_access_counted_get_x_number;
#[path = "direct_field_access_create_other_with_mt.rs"]
pub mod direct_field_access_create_other_with_mt;
#[path = "direct_field_access_create_other_without_mt.rs"]
pub mod direct_field_access_create_other_without_mt;
#[path = "direct_field_access_create_vec_2.rs"]
pub mod direct_field_access_create_vec_2;
#[path = "direct_field_access_get_non_zero_boolean.rs"]
pub mod direct_field_access_get_non_zero_boolean;
#[path = "direct_field_access_get_x_number.rs"]
pub mod direct_field_access_get_x_number;
#[path = "direct_field_access_get_y_number.rs"]
pub mod direct_field_access_get_y_number;
#[path = "direct_field_access_handler_hit_count.rs"]
pub mod direct_field_access_handler_hit_count;
#[path = "direct_field_access_increment_handler_hit_count.rs"]
pub mod direct_field_access_increment_handler_hit_count;
#[path = "direct_field_access_k_tag_other.rs"]
pub mod direct_field_access_k_tag_other;
#[path = "direct_field_access_k_tag_vec_2.rs"]
pub mod direct_field_access_k_tag_vec_2;
#[path = "direct_field_access_push_minus_one.rs"]
pub mod direct_field_access_push_minus_one;
#[path = "direct_field_access_reset_handler_hit_count.rs"]
pub mod direct_field_access_reset_handler_hit_count;
#[path = "ends_with.rs"]
pub mod ends_with;
#[path = "find_conformance_source_dir.rs"]
pub mod find_conformance_source_dir;
#[path = "get_first_luau_frame_debug_info.rs"]
pub mod get_first_luau_frame_debug_info;
#[path = "get_int_64.rs"]
pub mod get_int_64;
#[path = "get_or_create_atom.rs"]
pub mod get_or_create_atom;
#[path = "huge_function_load_failure_test_allocate.rs"]
pub mod huge_function_load_failure_test_allocate;
#[path = "id_inliner.rs"]
pub mod id_inliner;
#[path = "id_inliner_with_assert.rs"]
pub mod id_inliner_with_assert;
#[path = "int_64_add.rs"]
pub mod int_64_add;
#[path = "int_64_ctor.rs"]
pub mod int_64_ctor;
#[path = "int_64_div.rs"]
pub mod int_64_div;
#[path = "int_64_eq.rs"]
pub mod int_64_eq;
#[path = "int_64_idiv.rs"]
pub mod int_64_idiv;
#[path = "int_64_index.rs"]
pub mod int_64_index;
#[path = "int_64_le.rs"]
pub mod int_64_le;
#[path = "int_64_lt.rs"]
pub mod int_64_lt;
#[path = "int_64_mod.rs"]
pub mod int_64_mod;
#[path = "int_64_mul.rs"]
pub mod int_64_mul;
#[path = "int_64_newindex.rs"]
pub mod int_64_newindex;
#[path = "int_64_pow.rs"]
pub mod int_64_pow;
#[path = "int_64_sub.rs"]
pub mod int_64_sub;
#[path = "int_64_tostring.rs"]
pub mod int_64_tostring;
#[path = "int_64_unm.rs"]
pub mod int_64_unm;
#[path = "k_int_64_tag.rs"]
pub mod k_int_64_tag;
#[path = "limited_realloc.rs"]
pub mod limited_realloc;
#[path = "lua_collectgarbage.rs"]
pub mod lua_collectgarbage;
#[path = "lua_loadstring.rs"]
pub mod lua_loadstring;
#[path = "lua_silence.rs"]
pub mod lua_silence;
#[path = "lua_vec_2.rs"]
pub mod lua_vec_2;
#[path = "lua_vec_2_clone.rs"]
pub mod lua_vec_2_clone;
#[path = "lua_vec_2_dot.rs"]
pub mod lua_vec_2_dot;
#[path = "lua_vec_2_get.rs"]
pub mod lua_vec_2_get;
#[path = "lua_vec_2_index.rs"]
pub mod lua_vec_2_index;
#[path = "lua_vec_2_min.rs"]
pub mod lua_vec_2_min;
#[path = "lua_vec_2_namecall.rs"]
pub mod lua_vec_2_namecall;
#[path = "lua_vec_2_newindex.rs"]
pub mod lua_vec_2_newindex;
#[path = "lua_vec_2_push.rs"]
pub mod lua_vec_2_push;
#[path = "lua_vec_2_reenter.rs"]
pub mod lua_vec_2_reenter;
#[path = "lua_vector_cross.rs"]
pub mod lua_vector_cross;
#[path = "lua_vector_dot.rs"]
pub mod lua_vector_dot;
#[path = "lua_vector_index.rs"]
pub mod lua_vector_index;
#[path = "lua_vector_namecall.rs"]
pub mod lua_vector_namecall;
#[path = "lua_vertex.rs"]
pub mod lua_vertex;
#[path = "lua_vertex_clone.rs"]
pub mod lua_vertex_clone;
#[path = "lua_vertex_get.rs"]
pub mod lua_vertex_get;
#[path = "lua_vertex_index.rs"]
pub mod lua_vertex_index;
#[path = "lua_vertex_namecall.rs"]
pub mod lua_vertex_namecall;
#[path = "lua_vertex_newindex.rs"]
pub mod lua_vertex_newindex;
#[path = "lua_vertex_push.rs"]
pub mod lua_vertex_push;
#[path = "make_huge_function_source.rs"]
pub mod make_huge_function_source;
#[path = "multiple_yields.rs"]
pub mod multiple_yields;
#[path = "multiple_yields_continuation.rs"]
pub mod multiple_yields_continuation;
#[path = "multiple_yields_with_nested_call.rs"]
pub mod multiple_yields_with_nested_call;
#[path = "multiple_yields_with_nested_call_continuation.rs"]
pub mod multiple_yields_with_nested_call_continuation;
#[path = "nested_multiple_yield_helper.rs"]
pub mod nested_multiple_yield_helper;
#[path = "nested_multiple_yield_helper_continuation.rs"]
pub mod nested_multiple_yield_helper_continuation;
#[path = "nested_multiple_yield_helper_non_yielding.rs"]
pub mod nested_multiple_yield_helper_non_yielding;
#[path = "passthrough_call.rs"]
pub mod passthrough_call;
#[path = "passthrough_call_arg_reuse.rs"]
pub mod passthrough_call_arg_reuse;
#[path = "passthrough_call_arg_reuse_continuation.rs"]
pub mod passthrough_call_arg_reuse_continuation;
#[path = "passthrough_call_continuation.rs"]
pub mod passthrough_call_continuation;
#[path = "passthrough_call_more_results.rs"]
pub mod passthrough_call_more_results;
#[path = "passthrough_call_more_results_continuation.rs"]
pub mod passthrough_call_more_results_continuation;
#[path = "passthrough_call_varadic.rs"]
pub mod passthrough_call_varadic;
#[path = "passthrough_call_varadic_continuation.rs"]
pub mod passthrough_call_varadic_continuation;
#[path = "passthrough_call_with_state.rs"]
pub mod passthrough_call_with_state;
#[path = "passthrough_call_with_state_continuation.rs"]
pub mod passthrough_call_with_state_continuation;
#[path = "pcall_then_x_call.rs"]
pub mod pcall_then_x_call;
#[path = "pcall_then_x_call_continuation.rs"]
pub mod pcall_then_x_call_continuation;
#[path = "populate_rtti.rs"]
pub mod populate_rtti;
#[path = "push_int_64.rs"]
pub mod push_int_64;
#[path = "run_code.rs"]
pub mod run_code;
#[path = "run_conformance.rs"]
pub mod run_conformance;
#[path = "sealing_inliner.rs"]
pub mod sealing_inliner;
#[path = "setup_native_helpers.rs"]
pub mod setup_native_helpers;
#[path = "setup_userdata_helpers.rs"]
pub mod setup_userdata_helpers;
#[path = "setup_vector_helpers.rs"]
pub mod setup_vector_helpers;
#[path = "shared_code_allocator_module_id.rs"]
pub mod shared_code_allocator_module_id;
#[path = "single_yield.rs"]
pub mod single_yield;
#[path = "single_yield_continuation.rs"]
pub mod single_yield_continuation;
#[path = "slowly_overflow_stack.rs"]
pub mod slowly_overflow_stack;
#[path = "type_to_userdata_index.rs"]
pub mod type_to_userdata_index;
#[path = "update_direct_slot.rs"]
pub mod update_direct_slot;
#[path = "userdata_access.rs"]
pub mod userdata_access;
#[path = "userdata_access_bytecode_type.rs"]
pub mod userdata_access_bytecode_type;
#[path = "userdata_alignment_alloc.rs"]
pub mod userdata_alignment_alloc;
#[path = "userdata_alignment_dtor.rs"]
pub mod userdata_alignment_dtor;
#[path = "userdata_api_dtor_hits.rs"]
pub mod userdata_api_dtor_hits;
#[path = "userdata_api_inline_char_dtor.rs"]
pub mod userdata_api_inline_char_dtor;
#[path = "userdata_api_inline_int_dtor.rs"]
pub mod userdata_api_inline_int_dtor;
#[path = "userdata_api_tag_dtor.rs"]
pub mod userdata_api_tag_dtor;
#[path = "userdata_index_to_type.rs"]
pub mod userdata_index_to_type;
#[path = "userdata_metamethod.rs"]
pub mod userdata_metamethod;
#[path = "userdata_metamethod_bytecode_type.rs"]
pub mod userdata_metamethod_bytecode_type;
#[path = "userdata_namecall.rs"]
pub mod userdata_namecall;
#[path = "userdata_namecall_bytecode_type.rs"]
pub mod userdata_namecall_bytecode_type;
#[path = "vec_2_direct_index.rs"]
pub mod vec_2_direct_index;
#[path = "vec_2_direct_namecall.rs"]
pub mod vec_2_direct_namecall;
#[path = "vec_2_direct_newindex.rs"]
pub mod vec_2_direct_newindex;
#[path = "vector_access.rs"]
pub mod vector_access;
#[path = "vector_access_bytecode_type.rs"]
pub mod vector_access_bytecode_type;
#[path = "vector_namecall.rs"]
pub mod vector_namecall;
#[path = "vector_namecall_bytecode_type.rs"]
pub mod vector_namecall_bytecode_type;
#[path = "vertex_direct_index.rs"]
pub mod vertex_direct_index;
#[path = "vertex_direct_namecall.rs"]
pub mod vertex_direct_namecall;
#[path = "vertex_direct_newindex.rs"]
pub mod vertex_direct_newindex;
