[package]
name = "ulua-bytecode"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Luau bytecode format and builder (Rust)."
keywords = ["luau", "lua", "bytecode", "compiler"]
categories = ["compilers", "encoding"]

[lib]
crate-type = ["rlib"]

[dependencies]
memchr = { version = "2.8", default-features = false, features = ["alloc"] }
ulua-common = { path = "../ulua-common", version = "0.1.1" }

[features]
default = ["std"]
std = []
native = ["std"]
cli = ["native"]
native-codegen = ["native"]
wasm = []

