use core::ffi::c_char;

use ulua_common::records::{dense_hash_map::DenseHashMap, dense_hash_set::DenseHashSet};

use crate::{
  records::{
    allocator::Allocator, ast_array::AstArray, ast_attr::AstAttr,
    ast_declared_extern_type_property::AstDeclaredExternTypeProperty, ast_expr::AstExpr,
    ast_expr_table::Item as AstExprTableItem, ast_generic_type::AstGenericType,
    ast_generic_type_pack::AstGenericTypePack, ast_local::AstLocal, ast_name::AstName,
    ast_stat::AstStat, ast_table_prop::AstTableProp, ast_type::AstType, binding::Binding,
    comment::Comment, cst_expr_table::Item as CstExprTableItem,
    cst_type_table::Item as CstTypeTableItem, function::Function, hot_comment::HotComment,
    lexer::Lexer, location::Location, match_lexeme::MatchLexeme, parse_error::ParseError,
    parse_options::ParseOptions, position::Position,
  },
  type_aliases::{
    ast_argument_name::AstArgumentName, ast_class_member::AstClassMember, cst_node_map::CstNodeMap,
  },
};

#[derive(Debug)]
pub struct Parser {
  pub(crate) options: ParseOptions,
  pub(crate) lexer: Lexer,
  pub(crate) allocator: *mut Allocator,
  pub(crate) comment_locations: Vec<Comment>,
  pub(crate) hotcomments: Vec<HotComment>,
  pub(crate) hotcomment_header: bool,
  pub(crate) recursion_counter: u32,
  pub(crate) name_self: AstName,
  pub(crate) name_number: AstName,
  pub(crate) name_error: AstName,
  pub(crate) name_nil: AstName,
  pub(crate) end_mismatch_suspect: Option<MatchLexeme>,
  pub(crate) function_stack: Vec<Function>,
  pub(crate) type_function_depth: usize,
  pub(crate) local_map: DenseHashMap<AstName, *mut AstLocal>,
  pub(crate) local_stack: Vec<*mut AstLocal>,
  pub(crate) classes_within_module: DenseHashSet<AstName>,
  pub(crate) parse_errors: Vec<ParseError>,
  pub(crate) match_recovery_stop_on_token: Vec<u32>,
  pub(crate) declared_export_bindings: DenseHashMap<AstName, Location>,
  pub(crate) has_module_return: bool,
  pub(crate) scratch_attr: Vec<*mut AstAttr>,
  pub(crate) scratch_stat: Vec<*mut AstStat>,
  pub(crate) scratch_string: Vec<AstArray<c_char>>,
  pub(crate) scratch_string_2: Vec<AstArray<c_char>>,
  pub(crate) scratch_expr: Vec<*mut AstExpr>,
  pub(crate) scratch_expr_aux: Vec<*mut AstExpr>,
  pub(crate) scratch_binding: Vec<Binding>,
  pub(crate) scratch_local: Vec<*mut AstLocal>,
  pub(crate) scratch_table_type_props: Vec<AstTableProp>,
  pub(crate) scratch_cst_table_type_props: Vec<CstTypeTableItem>,
  pub(crate) scratch_type: Vec<*mut AstType>,
  pub(crate) scratch_declared_class_props: Vec<AstDeclaredExternTypeProperty>,
  pub(crate) scratch_class_declarations: Vec<AstClassMember>,
  pub(crate) scratch_item: Vec<AstExprTableItem>,
  pub(crate) scratch_cst_item: Vec<CstExprTableItem>,
  pub(crate) scratch_arg_name: Vec<AstArgumentName>,
  pub(crate) scratch_generic_types: Vec<*mut AstGenericType>,
  pub(crate) scratch_generic_type_packs: Vec<*mut AstGenericTypePack>,
  pub(crate) scratch_opt_arg_name: Vec<Option<AstArgumentName>>,
  pub(crate) scratch_position: Vec<Position>,
  pub(crate) scratch_position_2: Vec<Position>,
  pub(crate) scratch_data: String,
  pub(crate) cst_node_map: CstNodeMap,
}
