[package]
name = "ulua-repl-cli"
version = "0.1.5"
description = "Interactive Luau REPL (Rust)."
keywords = [ "luau", "lua", "repl", "interpreter", "cli" ]
categories = [ "command-line-utilities", "development-tools" ]

[package.edition]
workspace = true

[package.license]
workspace = true

[package.authors]
workspace = true

[package.repository]
workspace = true

[lib]
crate-type = [ "rlib" ]

[[bin]]
name = "ulua-repl"
path = "src/main.rs"

[dependencies.ulua-ast]
path = "../ulua-ast"
version = "0.1.5"

[dependencies.ulua-bytecode]
path = "../ulua-bytecode"
version = "0.1.5"

[dependencies.ulua-cli-lib]
path = "../ulua-cli-lib"
version = "0.1.5"

[dependencies.ulua-code-gen]
path = "../ulua-code-gen"
version = "0.1.5"

[dependencies.ulua-common]
path = "../ulua-common"
version = "0.1.5"

[dependencies.ulua-compiler]
path = "../ulua-compiler"
version = "0.1.5"

[dependencies.ulua-require]
path = "../ulua-require"
version = "0.1.5"

[dependencies.ulua-vm]
path = "../ulua-vm"
version = "0.1.5"

[dependencies.rustyline]
workspace = true

[dependencies.itoa]
workspace = true

[dependencies.signal-hook-registry]
workspace = true
